<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
marks=np.array([
    [78,81,74,90],
    [65,72,80,76],
    [92,88,95,91],
    [55,60,58,63],
    [84,79,86,88]
])

In [ ]:
marks[0]

array([78, 81, 74, 90])

In [ ]:
marks[0][-1]

np.int64(90)

In [ ]:
marks[1][-3]

np.int64(72)

In [ ]:
marks.shape

(5, 4)

In [ ]:
marks.ndim

2

In [ ]:
marks.size

20

In [ ]:
marks[1][1]

np.int64(72)

In [ ]:
marks[ :,0]

array([78, 65, 92, 55, 84])

In [ ]:
marks[ :,1]

array([81, 72, 88, 60, 79])

In [ ]:
marks[ :, :]

array([[78, 81, 74, 90],
       [65, 72, 80, 76],
       [92, 88, 95, 91],
       [55, 60, 58, 63],
       [84, 79, 86, 88]])

In [ ]:
marks[2:5,2:4]

array([[95, 91],
       [58, 63],
       [86, 88]])

In [ ]:
marks[ :3]

array([[78, 81, 74, 90],
       [65, 72, 80, 76],
       [92, 88, 95, 91]])

In [ ]:
marks[:,0:2]

array([[78, 81],
       [65, 72],
       [92, 88],
       [55, 60],
       [84, 79]])

In [ ]:
a=np.array([8,3,6])
print(np.argmin(a))

1
