<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q131

In [ ]:
message=input("Enter a message:")
morse={"A":".-","B":"-...","C":"-.-.","D":"-.."
        "E":".","F":"..-.","G":"--.","H":"..."
        "I":"..","J":".---","K":"-.-","L":".-.."
        "M":"--","N":"-.","O":"---","P":".--.",
       "Q":"--.-","R":".-.","S":"...","T":"-",
       "U":"..-","V":"...-","W":".--","X":"-.-.",
       "Y":"-.--","Z":"--..","0":"-----","1":".----",
       "2":"..---","3":"...--","4":"....-","5":".....",
       "6":"-....","7":"--...","8":"---..","9":"----."}
for char in morse.upper():
  if char in message:
    result=morse[char]=" "
  print("Morse code:",result)




SyntaxError: invalid syntax (2152721907.py, line 3)

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
scores=[78,82,80,45]
added_scores=[]
for score in scores:
  added_scores.append(score+5)
print(added_scores)

[83, 87, 85, 50]


In [ ]:
scores=np.array(scores)
scores + 5

array([83, 87, 85, 50])

In [ ]:
scores**2

array([6084, 6724, 6400, 2025])

In [ ]:
end_term_scores=np.array([30,45,27,34])
cat_marks=np.array([23,21,18,26])
assignment_scores=np.array([9,6,2,8])
end_term_scores+cat_marks+assignment_scores

array([62, 72, 47, 68])

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)

array([78, 91, 68, 54, 82, 47, 60, 78, 97, 58, 62, 50, 50, 63, 92, 75, 79,
       63, 42, 61, 92, 41, 63, 83, 69, 77, 41, 99, 60, 72, 51, 97, 61, 83,
       64, 88, 66, 98, 81, 67, 99, 55, 54, 86, 90, 83, 94, 91, 96, 42])

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)
scores=np.array(scores)
bonus_scores=scores+5
bonus_scores


array([ 83,  96,  73,  59,  87,  52,  65,  83, 102,  63,  67,  55,  55,
        68,  97,  80,  84,  68,  47,  66,  97,  46,  68,  88,  74,  82,
        46, 104,  65,  77,  56, 102,  66,  88,  69,  93,  71, 103,  86,
        72, 104,  60,  59,  91,  95,  88,  99,  96, 101,  47])

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)
scores=np.array(scores)
bonus_scores=scores+5
bonus_scores
scores[scores<=50 ]

array([47, 50, 50, 42, 41, 41, 42])

In [ ]:
scores[(scores<=50)].size

7

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)
scores=np.array(scores)
bonus_scores=scores+5
bonus_scores
scores[scores>=80]

array([91, 82, 97, 92, 92, 83, 99, 97, 83, 88, 98, 81, 99, 86, 90, 83, 94,
       91, 96])

In [ ]:
scores[scores>=80].size

19

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)
scores=np.array(scores)
np.mean(scores)


np.float64(71.86)

In [ ]:
np.random.seed(42)
scores=np.random.randint(40,100,50)
scores=np.array(scores)
bonus_scores=scores+5
np.mean(bonus_scores)

np.float64(76.86)

In [ ]:
scores<=95

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True])

In [ ]:
scores[scores<=95]

array([78, 91, 68, 54, 82, 47, 60, 78, 58, 62, 50, 50, 63, 92, 75, 79, 63,
       42, 61, 92, 41, 63, 83, 69, 77, 41, 60, 72, 51, 61, 83, 64, 88, 66,
       81, 67, 55, 54, 86, 90, 83, 94, 91, 42])

In [ ]:
scores=np.array([98,70,56,97])
scores[~(scores<=95)]

array([98, 97])

In [ ]:
~(scores<=95)

array([ True, False, False,  True])

In [ ]:
import numpy as np
scores=np.array([98,70,56,97,46])
scores[~(scores>95) & (scores>60) | scores<50 ]

array([46])

In [ ]:
scores=np.array([98,70,56,97,46])
np.where(scores<50,"Fail","Pass")

array(['Pass', 'Pass', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [ ]:
def stroupper(word):
  return word.upper()

In [ ]:
names = np.array(["john","mary","edward"])
for names in names:
 print(stroupper(names))

JOHN
MARY
EDWARD


In [ ]:
np.vectorize(stroupper)(names)

array('EDWARD', dtype='<U6')

In [ ]:
vectoupper = np.frompyfunc(stroupper,1,1)
vectoupper(names)

'EDWARD'

In [ ]:
def adder(num):
  return num + 5
adder(90)

95

In [ ]:
uadder = np.vectorize(adder)

In [ ]:
scores=np.array([90,45,67])
uadder(scores)

array([95, 50, 72])

In [ ]:
uadder2 = np.frompyfunc(adder,1,1)
uadder2(scores)

array([95, 50, 72], dtype=object)

In [ ]:
def add_two(num1,num2):
 return num1+num2

In [ ]:
arr_1=np.array([1,2,3])
arr_2=np.array([3,4,5])
uadd_two=np.vectorize(add_two)
uadd_two(arr_1,arr_2)

array([4, 6, 8])

In [ ]:
def stat(num1,num2):
  return (num1+num2), (num1+num2)/2

In [ ]:
ustat=np.frompyfunc(stat,2,2)
arr_1=np.array([1,2,3])
arr_2=np.array([3,4,5])
ustat(arr_1,arr_2)


(array([4, 6, 8], dtype=object), array([2.0, 3.0, 4.0], dtype=object))

In [ ]:
sum_of_arrs,mean_of_arrs=ustat(arr_1,arr_2)

In [ ]:
sum_of_arrs

array([4, 6, 8], dtype=object)

In [ ]:
mean_of_arrs

array([2.0, 3.0, 4.0], dtype=object)

In [ ]:
def summary(grade1,grade2,grade3):
  return(grade1+grade2+grade3),(grade1+grade2+grade3)/3


In [ ]:
import numpy as np
grades=np.array([82,74,60,56,47])

def summary(grades):
  grades=np.array([82,74,60,56,47])
  mean=(np.mean(grades))

print(np.mean(grades))
print(np.median(grades))
print(np.std(grades))
print(grades.dtype)
print(grades.size)
print(grades.shape)


63.8
60.0
12.592060990957755
int64
5
(5,)


In [ ]:
import numpy as np
grades=np.array([82,74,60,56,47])
print("\n Letter Grades:")
for grade in grades:
  if grade >=80:
    print(f"{grade}=A")
  elif grade >=70:
    print(f"{grade}=B")
  elif grade >=60:
    print(f"{grade}=C")
  elif grade >=50:
    print(f"{grade}=D")
  else:
    print(f"{grade}=E")







 Letter Grades:
82=A
74=B
60=C
56=D
47=E


In [ ]:
def summary(grades):
 return np.power(grades,2)
grades=np.array([82,74,60,56,47])
np.power(grades,2)


array([6724, 5476, 3600, 3136, 2209])